### ISSUE TITLE
Add CI workflow for generating ontology

### ISSUE THREAD

**Issue by EmteZogaf** [medizininformatik-initiative/fhir-ontology-generator#117]
The CI sould be changed to automatically generated the full ontology using the 

generate_full_ontology.sh

file of this repository, executing as follows:

```
bash generate_full_ontology.sh --all
```

to run the script successfully the following env vars have to be set:
export ONTOLOGY_SERVER_ADDRESS=${ONTOLOGY_SERVER_ADDRESS:-http://my-onto-server-address}
export PRIVATE_KEY=${PRIVATE_KEY:-path-to-key-file}
export SERVER_CERTIFICATE=${SERVER_CERTIFICATE:-path-to-cert-file}

Note that this requires a server certificate and private key, which were provided by @jpwiedekopf 
and should be used here.

This should create a number of files in example/fdpg-ontology.
In particular the files: 
elastic.zip
backend.zip
mapping.zip

All these files should then be attached to a release as assets.

**Comment by juliangruendner** [comment]
double check if the translations can be cached
