### ISSUE TITLE
Support composite attributes

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-ontology-generator#17]
The ontology generator should be extended to support composite attributes.

Composite attributes are attributes which result in a search where the identification of the right field in the FHIR resource depends on two input variables:

1. a code to identify the correct object within an array in the fhir resource
2. a value (quantitative or qualitative) which should be filtered

For the ontology to support this it has to generate different mappings for CQL and FHIR Search.

## FHIR Search

For FHIR Search the mapping for a composite attribute has to be extended for a attributeType composite-quantity or composite-concept.

The mapping has to also be extended for a compositeCode, which determines the first part of the composite search parameter to be used and will always be a code.

The mapping then also has to set the correct attributeSearchParameter as a composite search parameter. For example component-code-value-quantity.

The tool evaluating this will then based on the attributeType combine the compositeCode with the value using the attributeSearchParameter to create the FHIR search String.

Example mapping:

```json
[
  {
    "attributeSearchParameters": [
      {
        "attributeKey": {
          "code": "8480-6",
          "display": "Systolischer Blutdruck",
          "system": "http://loinc.org"
        },
        "attributeType": "composite-quantity",
        "attributeSearchParameter": "component-code-value-quantity",
        "compositeCode": {
          "code": "8480-6",
          "display": "Sistolic Bloodpressure",
          "system": "http://loinc.org"
        }
      }
    ],
    "context": {
      "code": "Laboruntersuchung",
      "display": "Laboruntersuchung",
      "system": "fdpg.mii.cds",
      "version": "1.0.0"
    },
    "key": {
      "code": "85354-9",
      "display": "Blood pressure panel with all children optional",
      "system": "http://loinc.org"
    },
    "fhirResourceType": "Observation",
    "termCodeSearchParameter": "code"
  }
]
```

## CQL

For CQL in a first implementation the attributePath should be generated to contain the filtering for the correct sub object of the FHIR resource (equivalent to the first part of the composite search param for FHIR search).

This will filter will also always be a coding that is filtered for to identify the right part of a FHIR resource.

```json
{
  "context": {
    "code": "Laboruntersuchung",
    "display": "Laboruntersuchung",
    "system": "fdpg.mii.cds",
    "version": "1.0.0"
  },
  "key": {
    "system": "http://loinc.org",
    "code": "85354-9",
    "display": "Blood pressure panel with all children optional"
  },
  "resourceType": "Observation",
  "attributeFhirPaths": [
    {
      "attributeType": "Quantity",
      "attributeKey": {
        "system": "http://loinc.org",
        "code": "8462-4",
        "display": "Diastolic blood pressure"
      },
      "attributePath": "component.where(code.coding.exists(system = 'http://loinc.org' and code = '8462-4')).value as Quantity"
    }
  ]
}
```

**Comment by geloro94** [comment]
merged: https://github.com/medizininformatik-initiative/fhir-ontology-generator/pull/45
