### ISSUE TITLE
Module Adjustment: Person - Add Vitalstatus and Todesursache 

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-ontology-generator#22]
Re-Add Vitalstatus and Todesursache to the ontology.

**Vitalstatus simplifier**: https://simplifier.net/mii-basismodul-person-2024/mii_pr_person_vitalstatus
**Todseursache simplifier**: https://simplifier.net/mii-basismodul-person-2024/mii_pr_person_todesursache

Template: https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7BF809802D-5681-4201-BA14-98985C64DC3A%7D&file=mii-new-module-person-2024_v1.xlsx&action=default&mobileredirect=true

**Note**: Both were part of the ontology before, but because of the mulitple use of the same terminology it can only be reasonably integrated in the UI for the october release, where the context is made explicit in the UI

**Comment by geloro94** [comment]
Todesursache cannot be implemented until https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/issues/69 is resolved.

**Comment by geloro94** [comment]
Created new issue for Todesursache:
https://github.com/medizininformatik-initiative/fhir-ontology-generator/issues/49
