### ISSUE TITLE
Re-Regenerate Ontology with 2024 modules

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-ontology-generator#24]
The ontology should be re-generated using the official 2024 releases where possible - leading to the following selection:

MII_DIAGNOSE = https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.diagnose/2024.0.0
MII_LAB = "de.medizininformatikinitiative.kerndatensatz.laborbefund 1.0.7-alpha1"
MII_MEDICATION = "de.medizininformatikinitiative.kerndatensatz.medikation 2.0.0-ballot1"
MII_PERSON = https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.person/2024.0.0
MII_PROCEDURE = https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.prozedur/2024.0.0
MII_SPECIMEN = "de.medizininformatikinitiative.kerndatensatz.biobank 1.0.3"
MII_CONSENT = "de.medizininformatikinitiative.kerndatensatz.consent 1.0.1"

**Comment by juliangruendner** [comment]
@geloro94 can you please give feedback why we did not use:
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.biobank/1.0.8
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.consent/1.0.7
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.laborbefund/1.0.6
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.medikation/2.0.0

**Comment by geloro94** [comment]
Done in https://github.com/medizininformatik-initiative/fhir-ontology-generator/releases/tag/v2.2.0
