### ISSUE TITLE
Add Elastic Search ontology generation

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-ontology-generator#29]
Add Elastic Search ontology generation (see: https://github.com/medizininformatik-initiative/feasibility-ontology-elasticsearch) to the ontology generator so that the input file used to initialise the elastic search of the new backend for the dataportal ui is automatically generated based on the ui tree and made available as part of the release and added to the backend.zip ontology folder, so that it can be read in and used in future deployments of the datenportal backend.

https://github.com/medizininformatik-initiative/feasibility-backend

**Comment by geloro94** [comment]
@juliangruendner @alexanderkiel I think on monday we discussed if this should be rather added to the backend. Please decide.

**Comment by juliangruendner** [comment]
> @juliangruendner @alexanderkiel I think on monday we discussed if this should be rather added to the backend. Please decide.

its decided- it  should be part of the ontology generator
