### ISSUE TITLE
Criteria search - Alphabetical sorting of criteria

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/fhir-ontology-generator#5]
The criteria should be sorted alphabetically in the search tree

**Comment by geloro94** [comment]
![grafik](https://user-images.githubusercontent.com/24481264/164724785-033547a8-4aee-4b5b-9bdf-7b2ba92af3cf.png)

Fixed in [359fc92](https://github.com/medizininformatik-initiative/fhir-ontology-generator/commit/359fc9278de0f2f6ac6f377a9a5ae17139026d66)
